<a href="https://colab.research.google.com/github/RyanKhurana9/Pytorch/blob/main/RNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [150]:
import pandas as pd

In [151]:
df=pd.read_csv("100_Unique_QA_Dataset.csv")

In [152]:
df.head()

                                          question      answer
0                   What is the capital of France?       Paris
1                  What is the capital of Germany?      Berlin
2               Who wrote 'To Kill a Mockingbird'?  Harper-Lee
3  What is the largest planet in our solar system?     Jupiter
4   What is the boiling point of water in Celsius?         100

In [153]:
df.shape[0] # total number of rows

90

In [154]:
#tokenize
def tokenize(text):
  text=text.lower()
  text=text.replace("?",'')
  text=text.replace("'",'')

  return text.split()

In [155]:
tokenize("Who wrote 'To Kill a Mockingbird'?")

['who', 'wrote', 'to', 'kill', 'a', 'mockingbird']

In [156]:
# vocab(unique word in dataset)
vocab={"<UNK>":0}#<UNK>->unknown

In [157]:
len(vocab)

1

In [158]:
def build_vocab(row):
  tokenize_question=tokenize(row['question'])
  tokenize_answer=tokenize(row['answer'])
  # merged_token
  merged_token=tokenize_question+tokenize_answer
  for word in merged_token:
    if word not in vocab:
      vocab[word]=len(vocab)
    else:
      continue
  return vocab

In [159]:
df.apply(build_vocab,axis=1)

0     {'<UNK>': 0, 'what': 1, 'is': 2, 'the': 3, 'ca...
1     {'<UNK>': 0, 'what': 1, 'is': 2, 'the': 3, 'ca...
2     {'<UNK>': 0, 'what': 1, 'is': 2, 'the': 3, 'ca...
3     {'<UNK>': 0, 'what': 1, 'is': 2, 'the': 3, 'ca...
4     {'<UNK>': 0, 'what': 1, 'is': 2, 'the': 3, 'ca...
                            ...
85    {'<UNK>': 0, 'what': 1, 'is': 2, 'the': 3, 'ca...
86    {'<UNK>': 0, 'what': 1, 'is': 2, 'the': 3, 'ca...
87    {'<UNK>': 0, 'what': 1, 'is': 2, 'the': 3, 'ca...
88    {'<UNK>': 0, 'what': 1, 'is': 2, 'the': 3, 'ca...
89    {'<UNK>': 0, 'what': 1, 'is': 2, 'the': 3, 'ca...
Length: 90, dtype: object

In [160]:
len(vocab)

324

In [161]:
tokenize("What is the capital of India")

['what', 'is', 'the', 'capital', 'of', 'india']

In [162]:
# convert word to numerical_indicies
def text_to_indices(text,vocab):
  indexed_text=[]
  for token in tokenize(text):
    if token in vocab:
      indexed_text.append(vocab[token])
    else:
      indexed_text.append("<UNK>")
  return indexed_text

In [163]:
text_to_indices("What is the capital of India",vocab)

[1, 2, 3, 4, 5, 73]

In [164]:
import torch
from torch.utils.data import Dataset,DataLoader

In [165]:
class QAdataset(Dataset):
  def __init__(self,df,vocab):
    self.df=df
    self.vocab=vocab
  def __len__(self):
    return df.shape[0]
  def __getitem__(self, index):
    numerical_question=text_to_indices(self.df.iloc[index]['question'],self.vocab)
    numerical_answer=text_to_indices(self.df.iloc[index]['answer'],self.vocab)
    return torch.tensor(numerical_question),torch.tensor(numerical_answer)

In [166]:
dataset=QAdataset(df,vocab)

In [167]:
len(dataset)

90

In [168]:
dataset[0]

(tensor([1, 2, 3, 4, 5, 6]), tensor([7]))

In [169]:
dataset[10
        ]

(tensor([ 1,  2,  3,  4,  5, 53]), tensor([54]))

In [170]:
df.iloc[10]

question    What is the capital of Japan?
answer                              Tokyo
Name: 10, dtype: object

In [171]:
dataloader=DataLoader(dataset,batch_size=1
                      ,shuffle=True)

In [172]:
len(dataloader)

90

In [173]:
for question ,answer in dataloader:
  print("Question:",question)
  print("answer:",answer[0])
  print("\n")

Question: tensor([[  1,   2,   3,   4,   5, 206]])
answer: tensor([207])


Question: tensor([[  1,   2,   3, 234,   5, 235]])
answer: tensor([131])


Question: tensor([[  1,   2,   3, 180, 181, 182, 183]])
answer: tensor([184])


Question: tensor([[ 42, 137,   2, 226,  12,   3, 227, 228]])
answer: tensor([155])


Question: tensor([[ 42, 200,   2,  14, 201, 202, 203, 204]])
answer: tensor([205])


Question: tensor([[ 10,  75,   3, 296,  19, 297]])
answer: tensor([298])


Question: tensor([[ 42, 216, 118, 217, 218,  19,  14, 219,  43]])
answer: tensor([220])


Question: tensor([[42, 18,  2, 62, 63,  3, 64, 18]])
answer: tensor([65])


Question: tensor([[ 42,  18, 118,   3, 186, 187]])
answer: tensor([188])


Question: tensor([[ 10, 140,   3, 141, 171,   5,   3,  70, 172]])
answer: tensor([173])


Question: tensor([[1, 2, 3, 4, 5, 8]])
answer: tensor([9])


Question: tensor([[ 1,  2,  3, 69,  5, 53]])
answer: tensor([260])


Question: tensor([[  1,   2,   3,   4,   5, 236, 237]])
answer: tensor([238])


Question: tensor([[10, 11, 12, 13, 14, 15]])
answer: tensor([16])


Question: tensor([[  1,   2,   3, 103,   5, 104,  19, 105]])
answer: tensor([106])


Question: tensor([[ 42, 250, 251, 118, 252, 253]])
answer: tensor([254])


Question: tensor([[10, 29,  3, 30, 31]])
answer: tensor([32])


Question: tensor([[ 42, 167,   2,   3,  17, 168, 169]])
answer: tensor([170])


Question: tensor([[ 42,   2,   3, 210, 137, 168, 211, 169]])
answer: tensor([113])


Question: tensor([[ 42, 318,   2,  62,  63,   3, 319,   5, 320]])
answer: tensor([321])


Question: tensor([[  1,   2,   3, 163, 164, 165,  83,  84]])
answer: tensor([166])


Question: tensor([[ 1,  2,  3, 92, 93, 94]])
answer: tensor([95])


Question: tensor([[ 10,  96,   3, 104, 239]])
answer: tensor([240])


Question: tensor([[ 10,  75, 208]])
answer: tensor([209])


Question: tensor([[ 10, 140,   3, 141, 142,  12, 143,  83,   3, 144]])
answer: tensor([145])


Question: tensor([[10, 55,  3, 56,  5, 57]])
answer: tensor([58])


Question: tensor([[ 42, 255,   2, 256,  83, 257, 258]])
answer: tensor([259])


Question: tensor([[  1,   2,   3, 221,   5, 222, 223, 224]])
answer: tensor([225])


Question: tensor([[ 1,  2,  3,  4,  5, 99]])
answer: tensor([100])


Question: tensor([[ 42, 137,   2,  62,  39,   3, 322, 323]])
answer: tensor([6])


Question: tensor([[  1,   2,   3,   4,   5, 286]])
answer: tensor([287])


Question: tensor([[ 78,  79, 288,  81,  19,  14, 289]])
answer: tensor([85])


Question: tensor([[ 42, 107,   2, 108,  19, 109]])
answer: tensor([110])


Question: tensor([[10,  2,  3, 66,  5, 67]])
answer: tensor([68])


Question: tensor([[ 1,  2,  3, 50, 51, 19,  3, 45]])
answer: tensor([52])


Question: tensor([[ 78,  79, 129,  81,  19,   3,  21,  22]])
answer: tensor([36])


Question: tensor([[ 42, 137, 118,   3, 247,   5, 248]])
answer: tensor([249])


Question: tensor([[ 10, 140,   3, 141, 270,  93, 271,   5,   3, 272]])
answer: tensor([273])


Question: tensor([[ 1,  2,  3, 24, 25,  5, 26, 19, 27]])
answer: tensor([28])


Question: tensor([[  1,   2,   3,  69,   5, 155]])
answer: tensor([156])


Question: tensor([[  1,   2,   3, 212,   5,  14, 213, 214]])
answer: tensor([215])


Question: tensor([[  1,   2,   3,  92, 137,  19,   3,  45]])
answer: tensor([185])


Question: tensor([[ 10,  75, 111]])
answer: tensor([112])


Question: tensor([[ 42,   2,   3, 274, 211, 275]])
answer: tensor([276])


Question: tensor([[  1,   2,   3, 141, 117,  83,   3, 277, 278]])
answer: tensor([121])


Question: tensor([[10, 96,  3, 97]])
answer: tensor([98])


Question: tensor([[ 42, 174,   2,  62,  39, 175, 176,  12, 177, 178]])
answer: tensor([179])


Question: tensor([[10, 75, 76]])
answer: tensor([77])


Question: tensor([[ 1,  2,  3, 69,  5,  3, 70, 71]])
answer: tensor([72])


Question: tensor([[  1,   2,   3,   4,   5, 113]])
answer: tensor([114])


Question: tensor([[  1,   2,   3,   4,   5, 279]])
answer: tensor([280])


Question: tensor([[ 42,  86,  87, 241, 242,  19,  39, 243]])
answer: tensor([244])


Question: tensor([[  1,  87, 229, 230, 231, 232]])
answer: tensor([233])


Question: tensor([[ 42, 117, 118,   3, 119,  94, 120]])
answer: tensor([121])


Question: tensor([[ 1,  2,  3, 33, 34,  5, 35]])
answer: tensor([36])


Question: tensor([[ 1,  2,  3,  4,  5, 53]])
answer: tensor([54])


Question: tensor([[ 78,  79, 195,  81,  19,   3, 196, 197, 198]])
answer: tensor([199])


Question: tensor([[  1,   2,   3,  37,  38,  39, 161]])
answer: tensor([162])


Question: tensor([[  1,   2,   3, 122, 123,  19,   3,  45]])
answer: tensor([124])


Question: tensor([[  1,   2,   3,   4,   5, 135]])
answer: tensor([136])


Question: tensor([[ 42, 137,   2, 138,  39, 139]])
answer: tensor([53])


Question: tensor([[  1,   2,   3,   4,   5, 109]])
answer: tensor([317])


Question: tensor([[  1,   2,   3,  37, 133,   5,  26]])
answer: tensor([134])


Question: tensor([[ 78,  79, 261, 151,  14, 262, 153]])
answer: tensor([36])


Question: tensor([[ 1,  2,  3,  4,  5, 73]])
answer: tensor([74])


Question: tensor([[  1,   2,   3,  17, 115,  83,  84]])
answer: tensor([116])


Question: tensor([[42, 86, 87, 88, 89, 39, 90]])
answer: tensor([91])


Question: tensor([[1, 2, 3, 4, 5, 6]])
answer: tensor([7])


Question: tensor([[ 10, 308,   3, 309, 310]])
answer: tensor([311])


Question: tensor([[ 42, 137,   2, 138,  39, 175, 269]])
answer: tensor([99])


Question: tensor([[  1,   2,   3, 146, 147,  19, 148]])
answer: tensor([149])


Question: tensor([[  1,   2,   3,  33,  34,   5, 245]])
answer: tensor([246])


Question: tensor([[ 42, 312,   2, 313,  62,  63,   3, 314, 315]])
answer: tensor([316])


Question: tensor([[78, 79, 80, 81, 82, 83, 84]])
answer: tensor([85])


Question: tensor([[ 10,  11, 189, 158, 190]])
answer: tensor([191])


Question: tensor([[ 10,  29, 130, 131]])
answer: tensor([132])


Question: tensor([[ 1,  2,  3, 37, 38, 39, 40]])
answer: tensor([41])


Question: tensor([[ 42, 263, 264,  14, 265, 266, 158, 267]])
answer: tensor([268])


Question: tensor([[ 1,  2,  3, 17, 18, 19, 20, 21, 22]])
answer: tensor([23])


Question: tensor([[ 1,  2,  3, 59, 25,  5, 26, 19, 60]])
answer: tensor([61])


Question: tensor([[ 42, 125,   2,  62,  63,   3, 126, 127]])
answer: tensor([128])


Question: tensor([[ 42,  18,   2,   3, 281,  12,   3, 282]])
answer: tensor([205])


Question: tensor([[ 42, 299, 300, 118,  14, 301, 302, 158, 303, 304, 305, 306]])
answer: tensor([307])


Question: tensor([[ 10,   2,  62,  63,   3, 283,   5, 284]])
answer: tensor([285])


Question: tensor([[ 10,  11, 157, 158, 159]])
answer: tensor([160])


Question: tensor([[ 42, 101,   2,   3,  17]])
answer: tensor([102])


Question: tensor([[  1,   2,   3, 146,  86,  19, 192, 193]])
answer: tensor([194])


Question: tensor([[ 78,  79, 150, 151,  14, 152, 153]])
answer: tensor([154])


Question: tensor([[ 42, 290, 291, 118, 292, 158, 293, 294]])
answer: tensor([295])


Question: tensor([[42, 43, 44, 45, 46, 47, 48]])
answer: tensor([49])

All sequences in a batch must have equal lengths for PyTorch's default DataLoader collation to stack them into a single tensor.

In [174]:
import torch.nn as nn

In [175]:
class RNNmodel(nn.Module):
  def __init__(self, vocab_size):
     super().__init__()
     # super -> refers to the parent class
     # it allows the child class to invoke the constructor of its parent class
     self.embedding = nn.Embedding(vocab_size, embedding_dim=50)
     self.rnn = nn.RNN(50, 64, batch_first=True)
     self.fc = nn.Linear(64, vocab_size)

  def forward(self, question):
    embedded_question = self.embedding(question)
    # self.rnn returns (output, hidden)
    output, final = self.rnn(embedded_question)
    # final has shape [1, batch_size, hidden_dim]. We squeeze it to [batch_size, hidden_dim]
    output = self.fc(final.squeeze(0))
    return output

In [176]:
len(vocab)

324

In [177]:
x=nn.Embedding(324,embedding_dim=50)
y=nn.RNN(50,64,batch_first=True)
z=nn.Linear(64,324)# The linear layer returns a vector of 324 scores (logits), one for each token in the vocabulary(# find the max)

In [178]:
dataset[0][0].shape# question

torch.Size([6])

In [179]:
dataset[0][0].reshape(1,6)

tensor([[1, 2, 3, 4, 5, 6]])

In [180]:
a=dataset[0][0].reshape(1,6)
print("shape of a:",a.shape)
# send this to embedding
b=x(a)
print("shape of b:",b.shape)
# send this to rnn
c,d=y(b)
print("shape of c:",c.shape)# sub hidden states
print("shape of d:",d.shape)# final hidden state
# send this to linear

shape of a: torch.Size([1, 6])
shape of b: torch.Size([1, 6, 50])
shape of c: torch.Size([1, 6, 64])
shape of d: torch.Size([1, 1, 64])

In [181]:
model = RNNmodel(len(vocab))

In [182]:
learning_rate=0.01
epochs=50

In [183]:
criterion=nn.CrossEntropyLoss()
optimizer=torch.optim.Adam(model.parameters(),lr=learning_rate)

In [184]:
for epoch in range(epochs):
  total_loss=0
  for question,answer in dataloader:
    optimizer.zero_grad()
    output=model(question)
    loss=criterion(output,answer[0])
    # backprop to calculate gradients
    loss.backward()
    # update weights
    optimizer.step()
    total_loss+=loss.item()
  print("epoch:",epoch+1,"loss:",total_loss/len(dataloader))

epoch: 1 loss: 6.0423002666897245
epoch: 2 loss: 3.859004282951355
epoch: 3 loss: 1.7547657060126463
epoch: 4 loss: 0.6119910633398427
epoch: 5 loss: 0.4447894969592906
epoch: 6 loss: 0.3422469241699825
epoch: 7 loss: 0.29166377517653425
epoch: 8 loss: 0.16668761942095847
epoch: 9 loss: 0.28066480747850925
epoch: 10 loss: 0.1816278096404858
epoch: 11 loss: 0.11219884771594985
epoch: 12 loss: 0.1488806101364187
epoch: 13 loss: 0.23753853436404218
epoch: 14 loss: 0.13482198094328243
epoch: 15 loss: 0.1747058130587296
epoch: 16 loss: 0.1142806402388184
epoch: 17 loss: 0.10017812601290643
epoch: 18 loss: 0.04390287235405089
epoch: 19 loss: 0.04089229017424966
epoch: 20 loss: 0.03491816056969886
epoch: 21 loss: 0.039556246073657854
epoch: 22 loss: 0.018936046437334476
epoch: 23 loss: 0.0038381793471570645
epoch: 24 loss: 0.003209733710779498
epoch: 25 loss: 0.0028234598285052925
epoch: 26 loss: 0.002540066112608959
epoch: 27 loss: 0.0023143935431208873
epoch: 28 loss: 0.002131012239260599
epoch: 29 loss: 0.001970626603643824
epoch: 30 loss: 0.0018630287732877252
epoch: 31 loss: 0.001708487272521274
epoch: 32 loss: 0.0016052821185439825
epoch: 33 loss: 0.0015025881849901957
epoch: 34 loss: 0.0014149059007953233
epoch: 35 loss: 0.0013336720724409033
epoch: 36 loss: 0.0012608794440489468
epoch: 37 loss: 0.0011864361970866514
epoch: 38 loss: 0.0011267493239655677
epoch: 39 loss: 0.0010647597816488188
epoch: 40 loss: 0.0010103114237103405
epoch: 41 loss: 0.0009624711205510215
epoch: 42 loss: 0.0009114305692492052
epoch: 43 loss: 0.0008678688816467507
epoch: 44 loss: 0.0008223653137166467
epoch: 45 loss: 0.0007824678808295479
epoch: 46 loss: 0.0007496719827435704
epoch: 47 loss: 0.0007095896341424022
epoch: 48 loss: 0.0006754589105387115
epoch: 49 loss: 0.000645980134464076
epoch: 50 loss: 0.0006140348710080919

logits = z(last_output)  # shape: (1, 324)probabilities = torch.softmax(logits, dim=1)  # shape: (1, 324)



- (1, 324) = 1 sample with 324 vocabulary scores.
- Softmax converts those 324 scores into probabilities.
- The output remains (1, 324), but the values now sum to 1.
- Argmax selects the token with the highest probability.

In [199]:
def predict(model,question,threshold=0.5):
  numerical_question=text_to_indices(question,vocab)
  print(numerical_question)
  # convert the list into a tesor
  numerical_question=torch.tensor(numerical_question)
  numerical_question=numerical_question.unsqueeze(0)
  print(numerical_question.shape)
  # send the numerical question to the model
  output=model(numerical_question)
  prob=torch.nn.functional.softmax(output,dim=1)
  val,indx=torch.max(prob,dim=1)
  if(val<threshold):
    print("I dont know")
  else:
    for key,value in vocab.items():
      if(value==indx):
        print(key)
        break

In [200]:
predict(model, "What is the largest planet in our solar system?")

[1, 2, 3, 17, 18, 19, 20, 21, 22]
torch.Size([1, 9])
jupiter